name: Deploy NodeJS project to function

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: func-roystonapplication
  NODE_VERSION: "14.x"
  GITHUB_ACTION_DEBUG: true
  RUNNER_DEBUG: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          pushd code
          npm ci
          npm run build --if-present
          npm run test --if-present
          popd
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: code/deploy
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
